name: variable-demo
run-name: this is variable demo

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: "echo $GITHUB_ACTION_PATH $CI $GITHUB_ACTION $GITHUB_ACTION_REPOSITORY"
